import type { Metadata } from 'next';
import { poppins } from '@/utils/fonts';
import './globals.css';
import Stepper from '@/components/molecules/stepper';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins}`}>{children}
      </body>
    </html>
  );
}
